language: cpp
dist: trusty
os: linux
env:
  global:
    - ARDUINO_VERSION=1.8.5
before_install:
  - wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/esp8266util
  -	arduino --pref boardsmanager.additional.urls=http://arduino.esp8266.com/stable/package_esp8266com_index.json --save-prefs
  - arduino --install-boards esp8266:esp8266
  - arduino --board esp8266:esp8266:generic --save-prefs
  - arduino --pref \"compiler.warning_level=all\" --save-prefs
