language: cpp
dist: trusty
os: linux
env:
  global:
    - ARDUINO_VERSION=1.8.5
before_install:
  - wget https://downloads.arduino.cc/arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - tar xf arduino-${ARDUINO_VERSION}-linux64.tar.xz
  - sudo mv arduino-${ARDUINO_VERSION} /usr/local/share/arduino
  - sudo ln -s /usr/local/share/arduino/arduino /usr/local/bin/arduino
install:
  - ln -s $PWD /usr/local/share/arduino/libraries/esp8266util

